# Generated by Django 4.2 on 2025-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_control_log'),
    ]

    operations = [
        # 算法模型新增字段
        migrations.AddField(
            model_name='algorithmmodel',
            name='model_precision',
            field=models.CharField(
                choices=[('FP32', 'FP32 (单精度浮点)'), ('FP16', 'FP16 (半精度浮点)'), ('INT8', 'INT8 (8位整数)')],
                default='FP32',
                max_length=10,
                verbose_name='模型精度'
            ),
        ),
        migrations.AddField(
            model_name='algorithmmodel',
            name='input_width',
            field=models.IntegerField(default=640, verbose_name='输入宽度'),
        ),
        migrations.AddField(
            model_name='algorithmmodel',
            name='input_height',
            field=models.IntegerField(default=640, verbose_name='输入高度'),
        ),
        migrations.AddField(
            model_name='algorithmmodel',
            name='nms_thresh',
            field=models.FloatField(
                default=0.45,
                help_text='非极大值抑制阈值，范围 0.0-1.0，默认 0.45',
                verbose_name='NMS阈值'
            ),
        ),
        migrations.AddField(
            model_name='algorithmmodel',
            name='conf_thresh',
            field=models.FloatField(
                default=0.25,
                help_text='分类置信度阈值，范围 0.0-1.0，默认 0.25',
                verbose_name='置信度阈值'
            ),
        ),

        # 布控模型新增推流质量配置字段
        migrations.AddField(
            model_name='control',
            name='push_video_codec',
            field=models.CharField(
                default='h264',
                help_text='视频编码器: h264, h265, vp8, vp9',
                max_length=20,
                verbose_name='推流视频编码器'
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='push_video_bitrate',
            field=models.IntegerField(
                default=2000,
                help_text='视频码率，单位kbps，默认2000 (2Mbps)',
                verbose_name='推流码率(kbps)'
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='push_video_fps',
            field=models.IntegerField(
                default=25,
                help_text='视频帧率，建议10-30fps，默认25',
                verbose_name='推流帧率(fps)'
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='push_video_width',
            field=models.IntegerField(
                default=1280,
                help_text='推流视频宽度，默认1280',
                verbose_name='推流宽度'
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='push_video_height',
            field=models.IntegerField(
                default=720,
                help_text='推流视频高度，默认720',
                verbose_name='推流高度'
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='push_video_gop',
            field=models.IntegerField(
                default=50,
                help_text='关键帧间隔，默认50帧',
                verbose_name='关键帧间隔(GOP)'
            ),
        ),
    ]
