# Generated by Django 4.2 on 2026-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_algorithm_pipeline_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.CharField(max_length=64, unique=True, verbose_name='lease_id')),
                ('node_id', models.CharField(max_length=100, verbose_name='node_id')),
                ('control_code', models.CharField(max_length=50, verbose_name='布控编号')),
                ('algorithm_code', models.CharField(max_length=50, verbose_name='算法编号')),
                ('package', models.CharField(blank=True, default='core', max_length=50, verbose_name='算法包')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '授权租约',
                'verbose_name_plural': '授权租约',
                'db_table': 'av_license_lease',
            },
        ),
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_json', models.TextField(blank=True, default='', verbose_name='license原文(JSON)')),
                ('license_id', models.CharField(blank=True, default='', max_length=100, verbose_name='license_id')),
                ('customer', models.CharField(blank=True, default='', max_length=200, verbose_name='customer')),
                ('cluster_id', models.CharField(blank=True, default='', max_length=128, verbose_name='cluster_id')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not_before')),
                ('not_after', models.DateTimeField(blank=True, null=True, verbose_name='not_after')),
                ('max_active_controls', models.IntegerField(default=0, verbose_name='最大活跃路数')),
                ('max_nodes', models.IntegerField(default=0, verbose_name='最大节点数')),
                ('packages_json', models.TextField(blank=True, default='[]', verbose_name='算法包列表(JSON)')),
                ('valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('last_error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='最后错误码')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='最后错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '授权状态',
                'verbose_name_plural': '授权状态',
                'db_table': 'av_license_state',
            },
        ),
    ]
