# Generated by Django 4.2 on 2026-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_algorithm_license_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, verbose_name='event_id')),
                ('sink_type', models.CharField(max_length=20, verbose_name='sink_type')),
                ('schema', models.CharField(default='beacon.event.v1', max_length=50, verbose_name='schema')),
                ('event_type', models.CharField(default='alarm.created', max_length=50, verbose_name='event_type')),
                ('event_source', models.CharField(blank=True, default='', max_length=50, verbose_name='event_source')),
                ('alarm_id', models.IntegerField(default=0, verbose_name='alarm_id')),
                ('control_code', models.CharField(blank=True, default='', max_length=50, verbose_name='control_code')),
                ('payload_json', models.TextField(blank=True, default='', verbose_name='payload_json')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='next_retry_at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent_at')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='last_error')),
                ('last_http_status', models.IntegerField(default=0, verbose_name='last_http_status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报警事件Outbox',
                'verbose_name_plural': '报警事件Outbox',
                'db_table': 'av_alarm_event_outbox',
            },
        ),
        migrations.AddIndex(
            model_name='alarmeventoutbox',
            index=models.Index(fields=['status', 'next_retry_at'], name='idx_alarm_outbox_status_retry'),
        ),
        migrations.AddIndex(
            model_name='alarmeventoutbox',
            index=models.Index(fields=['alarm_id'], name='idx_alarm_outbox_alarm_id'),
        ),
        migrations.AddConstraint(
            model_name='alarmeventoutbox',
            constraint=models.UniqueConstraint(fields=('event_id', 'sink_type'), name='uniq_alarm_event_outbox_event_sink'),
        ),
    ]
