# Generated by Django 4.2 on 2026-02-20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alarm_event_outbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudTenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="租户名称")),
                ("slug", models.CharField(max_length=100, unique=True, verbose_name="租户标识")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "云租户",
                "verbose_name_plural": "云租户",
                "db_table": "av_cloud_tenant",
            },
        ),
        migrations.CreateModel(
            name="CloudProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="app.cloudtenant"),
                ),
            ],
            options={
                "verbose_name": "云项目",
                "verbose_name_plural": "云项目",
                "db_table": "av_cloud_project",
            },
        ),
        migrations.CreateModel(
            name="CloudEdgeCluster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="集群名称")),
                ("edge_token_hash", models.CharField(blank=True, default="", max_length=128, verbose_name="edge_token_hash")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="最后上报时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edge_clusters", to="app.cloudproject"),
                ),
            ],
            options={
                "verbose_name": "云边缘集群",
                "verbose_name_plural": "云边缘集群",
                "db_table": "av_cloud_edge_cluster",
            },
        ),
        migrations.CreateModel(
            name="CloudAlarmEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=64, verbose_name="event_id")),
                ("event_type", models.CharField(blank=True, default="alarm.created", max_length=50, verbose_name="event_type")),
                ("event_source", models.CharField(blank=True, default="", max_length=50, verbose_name="event_source")),
                ("timestamp", models.DateTimeField(blank=True, null=True, verbose_name="事件时间")),
                ("node_code", models.CharField(blank=True, default="", max_length=100, verbose_name="node_code")),
                ("control_code", models.CharField(blank=True, default="", max_length=50, verbose_name="control_code")),
                ("desc", models.TextField(blank=True, default="", verbose_name="desc")),
                ("payload_json", models.TextField(blank=True, default="", verbose_name="payload_json")),
                ("image_bucket", models.CharField(blank=True, default="", max_length=200, verbose_name="image_bucket")),
                ("image_key", models.CharField(blank=True, default="", max_length=500, verbose_name="image_key")),
                ("image_content_type", models.CharField(blank=True, default="", max_length=100, verbose_name="image_content_type")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="接收时间")),
                (
                    "edge_cluster",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alarm_events", to="app.cloudedgecluster"),
                ),
            ],
            options={
                "verbose_name": "云端告警事件",
                "verbose_name_plural": "云端告警事件",
                "db_table": "av_cloud_alarm_event",
            },
        ),
        migrations.AddIndex(
            model_name="cloudalarmevent",
            index=models.Index(fields=["received_at"], name="idx_cloud_alarm_received"),
        ),
        migrations.AddIndex(
            model_name="cloudalarmevent",
            index=models.Index(fields=["edge_cluster"], name="idx_cloud_alarm_edge"),
        ),
        migrations.AddConstraint(
            model_name="cloudalarmevent",
            constraint=models.UniqueConstraint(fields=("edge_cluster", "event_id"), name="uniq_cloud_alarm_edge_event"),
        ),
    ]

