# Generated by Django 4.2 on 2026-02-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_cloud_saas_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=50, verbose_name="事件类型")),
                ("ok", models.BooleanField(default=False, verbose_name="是否成功")),
                ("operator", models.CharField(blank=True, default="", max_length=100, verbose_name="操作人")),
                ("source_ip", models.CharField(blank=True, default="", max_length=64, verbose_name="来源IP")),
                ("node_id", models.CharField(blank=True, default="", max_length=100, verbose_name="node_id")),
                ("control_code", models.CharField(blank=True, default="", max_length=50, verbose_name="布控编号")),
                ("algorithm_code", models.CharField(blank=True, default="", max_length=50, verbose_name="算法编号")),
                ("lease_id", models.CharField(blank=True, default="", max_length=64, verbose_name="lease_id")),
                ("error_code", models.CharField(blank=True, default="", max_length=50, verbose_name="错误码")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("detail_json", models.TextField(blank=True, default="", verbose_name="详情(JSON)")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "运维审计日志",
                "verbose_name_plural": "运维审计日志",
                "db_table": "av_ops_audit_log",
            },
        ),
        migrations.AddIndex(
            model_name="opsauditlog",
            index=models.Index(fields=["event_type", "create_time"], name="idx_ops_audit_evt_time"),
        ),
        migrations.AddIndex(
            model_name="opsauditlog",
            index=models.Index(fields=["ok", "create_time"], name="idx_ops_audit_ok_time"),
        ),
    ]

