# Generated by Django 4.2 on 2026-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_ops_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='draw_type',
            field=models.CharField(default='polygon', help_text='polygon=多边形区域, line=越线检测', max_length=20, verbose_name='绘制类型'),
        ),
        migrations.AddField(
            model_name='control',
            name='enable_hierarchical_algorithm',
            field=models.BooleanField(default=False, help_text='是否启用层级算法（检测后进行二级处理）', verbose_name='启用层级算法'),
        ),
        migrations.AddField(
            model_name='control',
            name='enable_tracking',
            field=models.BooleanField(default=False, help_text='越线检测需要启用追踪功能', verbose_name='启用目标追踪'),
        ),
        migrations.AddField(
            model_name='control',
            name='line_coordinates',
            field=models.CharField(blank=True, default='', help_text='格式：x1,y1,x2,y2（归一化坐标0-1）', max_length=100, verbose_name='越线检测线段坐标'),
        ),
        migrations.AddField(
            model_name='control',
            name='line_violation_direction',
            field=models.CharField(default='both', help_text='both=双向, forward=正向, backward=反向', max_length=20, verbose_name='违规方向'),
        ),
        migrations.AddField(
            model_name='control',
            name='secondary_algorithm_code',
            field=models.CharField(blank=True, default='', help_text='二级算法编号（可选）', max_length=50, verbose_name='二级算法编号'),
        ),
        migrations.AddField(
            model_name='control',
            name='secondary_api_url',
            field=models.CharField(blank=True, default='', help_text='二级算法API地址（可选）', max_length=200, verbose_name='二级算法API地址'),
        ),
        migrations.AddField(
            model_name='control',
            name='secondary_conf_thresh',
            field=models.FloatField(default=0.25, help_text='二级算法置信度阈值，默认0.25', verbose_name='二级算法置信度阈值'),
        ),
        migrations.AlterField(
            model_name='algorithmmodel',
            name='algorithm_subtype',
            field=models.CharField(choices=[('detection', '检测'), ('classification', '分类'), ('tracking', '追踪'), ('behavior', '行为')], default='detection', help_text='detection=检测, classification=分类, tracking=追踪, behavior=行为', max_length=20, verbose_name='算法子类型'),
        ),
    ]
