# Generated by Django 4.2 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_control_draw_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensestate",
            name="package_limits_json",
            field=models.TextField(blank=True, default="{}", verbose_name="算法包限额(JSON)"),
        ),
    ]

