# Generated by Django 4.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_license_package_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="osd_image_alpha",
            field=models.FloatField(
                default=1.0,
                help_text="全局透明度（0~1），默认 1.0",
                verbose_name="OSD贴图透明度",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_image_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="贴图路径（建议 png，支持 alpha）；为空表示不贴图",
                max_length=500,
                verbose_name="OSD贴图路径",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_image_scale",
            field=models.FloatField(
                default=1.0,
                help_text="缩放倍数（>0），默认 1.0",
                verbose_name="OSD贴图缩放",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_image_x",
            field=models.IntegerField(
                default=10,
                help_text="贴图左上角 X 坐标（像素）",
                verbose_name="OSD贴图X坐标",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_image_y",
            field=models.IntegerField(
                default=10,
                help_text="贴图左上角 Y 坐标（像素）",
                verbose_name="OSD贴图Y坐标",
            ),
        ),
    ]

