# Generated by Django 4.2 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_control_osd_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="alarm_cover_custom_index",
            field=models.IntegerField(
                default=0,
                help_text="alarm_cover_position=custom 时生效；0 表示使用默认策略",
                verbose_name="报警封面自定义帧序号",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="alarm_cover_position",
            field=models.CharField(
                default="front",
                help_text="front=触发帧, middle=中间帧, back=最后帧, custom=自定义帧序号",
                max_length=20,
                verbose_name="报警封面位置",
            ),
        ),
    ]

