# Generated by Django 4.2 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_control_alarm_cover_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="draw_type",
            field=models.IntegerField(
                default=1,
                help_text="1=画框, 0=不画框",
                verbose_name="画框类型",
            ),
        ),
    ]

