# Generated by Django 4.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alarm_draw_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='polygon',
            field=models.TextField(
                default='',
                help_text='多区域格式: region1;region2;... 每个region为归一化坐标 x,y 成对列表（0~1）',
                verbose_name='绘制区域坐标点',
            ),
        ),
    ]

