# Generated by Django 4.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_control_polygon_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='enable_hw_decode',
            field=models.BooleanField(
                default=False,
                help_text='仅用于硬件解码路数配额/调度；不启用时不占用 maxHardwareDecodeChannels',
                verbose_name='启用硬解码配额',
            ),
        ),
        migrations.AddField(
            model_name='control',
            name='enable_hw_encode',
            field=models.BooleanField(
                default=False,
                help_text='仅用于硬件编码路数配额/调度；不启用时不占用 maxHardwareEncodeChannels',
                verbose_name='启用硬编码配额',
            ),
        ),
    ]

