# Generated by Django 4.2 on 2026-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_control_hw_codec_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="osd_algo_x",
            field=models.IntegerField(
                default=20,
                help_text="画面叠加：算法名文字起点 X 坐标（像素），默认 20",
                verbose_name="算法名起点X",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_algo_y",
            field=models.IntegerField(
                default=80,
                help_text="画面叠加：算法名文字起点 Y 坐标（像素），默认 80",
                verbose_name="算法名起点Y",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_fps_x",
            field=models.IntegerField(
                default=20,
                help_text="画面叠加：FPS文字起点 X 坐标（像素），默认 20",
                verbose_name="FPS起点X",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="osd_fps_y",
            field=models.IntegerField(
                default=140,
                help_text="画面叠加：FPS文字起点 Y 坐标（像素），默认 140",
                verbose_name="FPS起点Y",
            ),
        ),
    ]
