# Generated by Django 4.2 on 2026-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_algorithm_behavior_api_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithmmodel",
            name="algorithm_type",
            field=models.IntegerField(
                choices=[(0, "基础算法"), (1, "行为算法"), (2, "业务算法")],
                default=0,
                verbose_name="算法类型",
            ),
        ),
    ]
