# Generated by Django 4.2 on 2026-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_algorithmmodel_algorithm_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="region_index",
            field=models.IntegerField(
                default=-1,
                help_text="多区域触发的区域下标（0-based）；-1=未知/不适用",
                verbose_name="区域编号",
            ),
        ),
    ]

