# Generated by Django 4.2 on 2026-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alarm_region_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="feature_algorithm_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="算法流程模式7/9使用的特征算法（可选：FaceNet/ReID等）",
                max_length=50,
                verbose_name="特征算法编号",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="feature_config",
            field=models.TextField(
                blank=True,
                default="{}",
                help_text="JSON格式的特征算法参数配置",
                verbose_name="特征算法配置",
            ),
        ),
    ]

