# Generated by Django 4.2 on 2026-03-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0036_control_prompt_and_perf_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, verbose_name="key")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "permissions_json",
                    models.TextField(
                        blank=True, default="", verbose_name="permissions_json"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="app.cloudtenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "云角色",
                "verbose_name_plural": "云角色",
                "db_table": "av_cloud_role",
            },
        ),
        migrations.CreateModel(
            name="CloudUserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认租户"),
                ),
                (
                    "resource_scope_json",
                    models.TextField(
                        blank=True, default="", verbose_name="resource_scope_json"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="app.cloudrole",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="app.cloudtenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "云成员",
                "verbose_name_plural": "云成员",
                "db_table": "av_cloud_user_membership",
            },
        ),
        migrations.AddIndex(
            model_name="cloudusermembership",
            index=models.Index(
                fields=["user", "tenant"], name="idx_cudmem_user_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="cloudusermembership",
            index=models.Index(
                fields=["tenant", "enabled"], name="idx_cudmem_tenant_enabled"
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudusermembership",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant"), name="uniq_cloud_membership_user_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="cloudrole",
            index=models.Index(
                fields=["tenant", "key"], name="idx_cloud_role_tenant_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uniq_cloud_role_tenant_key"
            ),
        ),
    ]
