# Generated by Django 4.2 on 2026-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_cloud_multitenancy_rbac"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudtenant",
            name="branding_json",
            field=models.TextField(
                blank=True, default="", verbose_name="branding_json"
            ),
        ),
    ]
