# Generated by Django 4.2 on 2026-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_cloud_tenant_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "token_prefix",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="token前缀"
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="token_hash"
                    ),
                ),
                (
                    "scopes_json",
                    models.TextField(
                        blank=True, default="[]", verbose_name="scopes(JSON)"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="吊销时间"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="创建人"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "av_api_key",
            },
        ),
        migrations.AlterField(
            model_name="algorithmmodel",
            name="algorithm_subtype",
            field=models.CharField(
                choices=[
                    ("detection", "检测"),
                    ("classification", "分类"),
                    ("tracking", "追踪"),
                    ("behavior", "行为"),
                    ("ocr", "OCR"),
                ],
                default="detection",
                help_text="detection=检测, classification=分类, tracking=追踪, behavior=行为",
                max_length=20,
                verbose_name="算法子类型",
            ),
        ),
        migrations.AlterField(
            model_name="algorithmmodel",
            name="behavior_api_version",
            field=models.IntegerField(
                choices=[
                    (1, "APIv1（API 完整输出 happen）"),
                    (2, "APIv2（API 输出 detects，本地内置行为后处理）"),
                    (3, "APIv3（API 输出 happen；请求同时携带 full+roi 图片）"),
                ],
                default=1,
                help_text="仅对行为/业务算法的自定义API生效：v1=API直接返回happen；v2=API返回detects，本地内置行为再判定；v3=API直接返回happen，且请求包含额外ROI图片字段",
                verbose_name="行为API版本",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["token_hash"], name="idx_api_key_hash"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["enabled", "expires_at"], name="idx_api_key_enabled_exp"
            ),
        ),
    ]
