# Generated by Django 4.2 on 2026-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLockout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="用户名")),
                (
                    "source_ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="来源IP"
                    ),
                ),
                ("failures", models.IntegerField(default=0, verbose_name="失败次数")),
                (
                    "first_failure_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次失败时间"
                    ),
                ),
                (
                    "last_failure_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后失败时间"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="锁定至"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "登录锁定",
                "verbose_name_plural": "登录锁定",
                "db_table": "av_login_lockout",
            },
        ),
        migrations.AddIndex(
            model_name="loginlockout",
            index=models.Index(fields=["locked_until"], name="idx_login_lockout_until"),
        ),
        migrations.AddIndex(
            model_name="loginlockout",
            index=models.Index(
                fields=["username", "source_ip"], name="idx_login_lockout_user_ip"
            ),
        ),
        migrations.AddConstraint(
            model_name="loginlockout",
            constraint=models.UniqueConstraint(
                fields=("username", "source_ip"), name="uniq_login_lockout_user_ip"
            ),
        ),
    ]
