# Generated by Django 4.2 on 2026-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_control_alarm_image_draw_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenselease",
            name="stream_code",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="视频流编号"),
        ),
    ]
