# Generated by Django 4.2.21 on 2026-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0049_streamtalkbackconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudedgecluster",
            name="edge_admin_base_url",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="edge_admin_base_url"),
        ),
        migrations.AddField(
            model_name="cloudedgecluster",
            name="edge_openapi_token",
            field=models.TextField(blank=True, default="", verbose_name="edge_openapi_token"),
        ),
        migrations.AddField(
            model_name="cloudedgecluster",
            name="node_code",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="node_code"),
        ),
        migrations.AddField(
            model_name="cloudedgecluster",
            name="remark",
            field=models.TextField(blank=True, default="", verbose_name="remark"),
        ),
    ]
