# Generated by Django 5.2.9 on 2026-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0057_alarm_filter_preset_sharing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithmmodel",
            name="algorithm_subtype",
            field=models.CharField(
                choices=[
                    ("detection", "检测"),
                    ("classification", "分类"),
                    ("tracking", "追踪"),
                    ("speech", "语音/ASR"),
                    ("behavior", "行为"),
                    ("ocr", "OCR"),
                ],
                default="detection",
                help_text="detection=检测, classification=分类, tracking=追踪, speech=语音/ASR, behavior=行为",
                max_length=20,
                verbose_name="算法子类型",
            ),
        ),
    ]
