# Generated by Django 4.2 on 2026-05-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0059_control_push_stream_blank_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalHumanAiDiagnosisConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="enabled")),
                (
                    "base_url",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="base_url"
                    ),
                ),
                (
                    "api_key",
                    models.TextField(blank=True, default="", verbose_name="api_key"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="model"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.2, verbose_name="temperature"),
                ),
                (
                    "alert_system_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="alert_system_prompt"
                    ),
                ),
                (
                    "log_system_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="log_system_prompt"
                    ),
                ),
                (
                    "connect_timeout_ms",
                    models.IntegerField(
                        default=10000, verbose_name="connect_timeout_ms"
                    ),
                ),
                (
                    "read_timeout_ms",
                    models.IntegerField(default=60000, verbose_name="read_timeout_ms"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human AI Diagnosis Config",
                "verbose_name_plural": "Digital Human AI Diagnosis Config",
                "db_table": "dh_system_ai_config",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="alert_type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "alert_module_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="alert_module_text",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        default="warning",
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "diagnosis_status",
                    models.CharField(
                        blank=True,
                        default="skipped",
                        max_length=20,
                        verbose_name="diagnosis_status",
                    ),
                ),
                (
                    "diagnosis_text",
                    models.TextField(
                        blank=True, default="", verbose_name="diagnosis_text"
                    ),
                ),
                (
                    "diagnosis_error",
                    models.TextField(
                        blank=True, default="", verbose_name="diagnosis_error"
                    ),
                ),
                (
                    "first_occurred_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="first_occurred_at"
                    ),
                ),
                (
                    "last_occurred_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last_occurred_at"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved_at"
                    ),
                ),
                (
                    "dingtalk_push_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="dingtalk_push_status",
                    ),
                ),
                (
                    "dingtalk_route_region",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="dingtalk_route_region",
                    ),
                ),
                (
                    "dingtalk_owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="dingtalk_owner_name",
                    ),
                ),
                (
                    "dingtalk_owner_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="dingtalk_owner_phone",
                    ),
                ),
                (
                    "dingtalk_message_preview",
                    models.TextField(
                        blank=True, default="", verbose_name="dingtalk_message_preview"
                    ),
                ),
                (
                    "dingtalk_error",
                    models.TextField(
                        blank=True, default="", verbose_name="dingtalk_error"
                    ),
                ),
                (
                    "dingtalk_push_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dingtalk_push_time"
                    ),
                ),
                (
                    "timeline_json",
                    models.TextField(
                        blank=True, default="[]", verbose_name="timeline_json"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Alert",
                "verbose_name_plural": "Digital Human Alerts",
                "db_table": "dh_alert_record",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanAlertRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="region"
                    ),
                ),
                (
                    "webhook",
                    models.TextField(blank=True, default="", verbose_name="webhook"),
                ),
                (
                    "secret",
                    models.TextField(blank=True, default="", verbose_name="secret"),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="owner_name",
                    ),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="owner_phone",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_default_route",
                    models.BooleanField(default=False, verbose_name="is_default_route"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Alert Route",
                "verbose_name_plural": "Digital Human Alert Routes",
                "db_table": "dh_alert_dingtalk_route",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanAlertRouteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="enabled")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Alert Route Config",
                "verbose_name_plural": "Digital Human Alert Route Config",
                "db_table": "dh_alert_dingtalk_config",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_code",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="device_code",
                    ),
                ),
                (
                    "agent_device_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="agent_device_id",
                    ),
                ),
                (
                    "machine_code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="machine_code"
                    ),
                ),
                (
                    "machine_mac",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="machine_mac",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="tenant_name",
                    ),
                ),
                (
                    "registered_by_jwt_account_uuid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="registered_by_jwt_account_uuid",
                    ),
                ),
                (
                    "registered_by_jwt_tenant_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="registered_by_jwt_tenant_name",
                    ),
                ),
                (
                    "authorization_enabled",
                    models.BooleanField(
                        default=False, verbose_name="authorization_enabled"
                    ),
                ),
                (
                    "authorization_status",
                    models.CharField(
                        default="PENDING",
                        max_length=20,
                        verbose_name="authorization_status",
                    ),
                ),
                (
                    "authorization_valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="authorization_valid_from"
                    ),
                ),
                (
                    "authorization_valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="authorization_valid_until"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="display_name",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="region"
                    ),
                ),
                (
                    "rustdesk_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="rustdesk_id",
                    ),
                ),
                (
                    "rustdesk_password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="rustdesk_password",
                    ),
                ),
                (
                    "agent_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="agent_token",
                    ),
                ),
                (
                    "computer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="computer_name",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="mac_address",
                    ),
                ),
                (
                    "os_name",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="os_name"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="os_version",
                    ),
                ),
                (
                    "os_user",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="os_user"
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="processor"
                    ),
                ),
                (
                    "processor_architecture",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="processor_architecture",
                    ),
                ),
                (
                    "local_ip",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="local_ip"
                    ),
                ),
                (
                    "system_uptime",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="system_uptime",
                    ),
                ),
                ("cpu_usage", models.FloatField(default=0.0, verbose_name="cpu_usage")),
                ("gpu_usage", models.FloatField(default=0.0, verbose_name="gpu_usage")),
                (
                    "memory_usage",
                    models.FloatField(default=0.0, verbose_name="memory_usage"),
                ),
                (
                    "disk_usage",
                    models.FloatField(default=0.0, verbose_name="disk_usage"),
                ),
                (
                    "net_latency_ms",
                    models.IntegerField(default=0, verbose_name="net_latency_ms"),
                ),
                (
                    "bandwidth_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="bandwidth_text",
                    ),
                ),
                (
                    "network_status_json",
                    models.TextField(
                        blank=True, default="", verbose_name="network_status_json"
                    ),
                ),
                (
                    "service_status_json",
                    models.TextField(
                        blank=True, default="", verbose_name="service_status_json"
                    ),
                ),
                (
                    "hardware_devices_json",
                    models.TextField(
                        blank=True, default="", verbose_name="hardware_devices_json"
                    ),
                ),
                (
                    "remote_monitor_json",
                    models.TextField(
                        blank=True, default="", verbose_name="remote_monitor_json"
                    ),
                ),
                (
                    "active_window_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="active_window_title",
                    ),
                ),
                (
                    "active_window_process",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="active_window_process",
                    ),
                ),
                (
                    "screenshot_base64",
                    models.TextField(
                        blank=True, default="", verbose_name="screenshot_base64"
                    ),
                ),
                (
                    "peripheral_cam",
                    models.BooleanField(default=False, verbose_name="peripheral_cam"),
                ),
                (
                    "peripheral_mic",
                    models.BooleanField(default=False, verbose_name="peripheral_mic"),
                ),
                (
                    "service_stream",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="service_stream"
                    ),
                ),
                (
                    "service_llm",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="service_llm"
                    ),
                ),
                (
                    "alert_window_enabled",
                    models.BooleanField(
                        default=False, verbose_name="alert_window_enabled"
                    ),
                ),
                (
                    "alert_window_weekdays_json",
                    models.TextField(
                        blank=True,
                        default="[]",
                        verbose_name="alert_window_weekdays_json",
                    ),
                ),
                (
                    "alert_window_start_time",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=8,
                        verbose_name="alert_window_start_time",
                    ),
                ),
                (
                    "alert_window_end_time",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=8,
                        verbose_name="alert_window_end_time",
                    ),
                ),
                (
                    "last_report_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last_report_time"
                    ),
                ),
                (
                    "last_online_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last_online_time"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Device",
                "verbose_name_plural": "Digital Human Devices",
                "db_table": "dh_device",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanDeviceMetricHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_at", models.DateTimeField(verbose_name="reported_at")),
                (
                    "status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="status"
                    ),
                ),
                ("cpu_usage", models.FloatField(default=0.0, verbose_name="cpu_usage")),
                ("gpu_usage", models.FloatField(default=0.0, verbose_name="gpu_usage")),
                (
                    "memory_usage",
                    models.FloatField(default=0.0, verbose_name="memory_usage"),
                ),
                (
                    "disk_usage",
                    models.FloatField(default=0.0, verbose_name="disk_usage"),
                ),
                (
                    "net_latency_ms",
                    models.IntegerField(default=0, verbose_name="net_latency_ms"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Device Metric History",
                "verbose_name_plural": "Digital Human Device Metric Histories",
                "db_table": "dh_device_metric_history",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanHumanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="time")),
                (
                    "level",
                    models.CharField(
                        blank=True, default="INFO", max_length=16, verbose_name="level"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="module"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="message"),
                ),
                (
                    "diagnosis_status",
                    models.CharField(
                        blank=True,
                        default="skipped",
                        max_length=20,
                        verbose_name="diagnosis_status",
                    ),
                ),
                (
                    "diagnosis_text",
                    models.TextField(
                        blank=True, default="", verbose_name="diagnosis_text"
                    ),
                ),
                (
                    "diagnosis_error",
                    models.TextField(
                        blank=True, default="", verbose_name="diagnosis_error"
                    ),
                ),
                (
                    "structured_json",
                    models.TextField(
                        blank=True, default="", verbose_name="structured_json"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human Human Log",
                "verbose_name_plural": "Digital Human Human Logs",
                "db_table": "dh_human_log",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanJwtAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_uuid",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="account_uuid"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="project_name",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="tenant_name"
                    ),
                ),
                (
                    "secret_hash",
                    models.CharField(max_length=64, verbose_name="secret_hash"),
                ),
                (
                    "secret_mask",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="secret_mask",
                    ),
                ),
                (
                    "token_ttl_minutes",
                    models.IntegerField(default=30, verbose_name="token_ttl_minutes"),
                ),
                (
                    "credential_version",
                    models.IntegerField(default=1, verbose_name="credential_version"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "last_token_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last_token_issued_at"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
            ],
            options={
                "verbose_name": "Digital Human JWT Account",
                "verbose_name_plural": "Digital Human JWT Accounts",
                "db_table": "dh_jwt_account",
            },
        ),
        migrations.AddIndex(
            model_name="digitalhumanjwtaccount",
            index=models.Index(fields=["tenant_name"], name="idx_dhjwt_tenant"),
        ),
        migrations.AddIndex(
            model_name="digitalhumanjwtaccount",
            index=models.Index(fields=["enabled"], name="idx_dhjwt_enabled"),
        ),
        migrations.AddField(
            model_name="digitalhumanhumanlog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_log_rows",
                to="app.digitalhumandevice",
                verbose_name="device",
            ),
        ),
        migrations.AddField(
            model_name="digitalhumandevicemetrichistory",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_rows",
                to="app.digitalhumandevice",
                verbose_name="device",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevice",
            index=models.Index(
                fields=["authorization_status"], name="idx_dhdev_auth_status"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevice",
            index=models.Index(fields=["tenant_name"], name="idx_dhdev_tenant"),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevice",
            index=models.Index(fields=["region"], name="idx_dhdev_region"),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevice",
            index=models.Index(
                fields=["last_report_time"], name="idx_dhdev_last_report"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumanalertroute",
            index=models.Index(fields=["region"], name="idx_dhroute_region"),
        ),
        migrations.AddIndex(
            model_name="digitalhumanalertroute",
            index=models.Index(
                fields=["active", "is_default_route"], name="idx_dhroute_active_default"
            ),
        ),
        migrations.AddField(
            model_name="digitalhumanalert",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rows",
                to="app.digitalhumandevice",
                verbose_name="device",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumanhumanlog",
            index=models.Index(fields=["time"], name="idx_dhlog_time"),
        ),
        migrations.AddIndex(
            model_name="digitalhumanhumanlog",
            index=models.Index(fields=["device", "time"], name="idx_dhlog_device_time"),
        ),
        migrations.AddIndex(
            model_name="digitalhumanhumanlog",
            index=models.Index(
                fields=["level", "module"], name="idx_dhlog_level_module"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevicemetrichistory",
            index=models.Index(
                fields=["device", "reported_at"], name="idx_dhmet_device_time"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumandevicemetrichistory",
            index=models.Index(fields=["reported_at"], name="idx_dhmet_reported"),
        ),
        migrations.AddIndex(
            model_name="digitalhumanalert",
            index=models.Index(
                fields=["status", "level"], name="idx_dhalert_status_level"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumanalert",
            index=models.Index(
                fields=["device", "status"], name="idx_dhalert_device_status"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumanalert",
            index=models.Index(
                fields=["last_occurred_at"], name="idx_dhalert_last_time"
            ),
        ),
    ]
