# Generated by Django 4.2 on 2026-05-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0060_digitalhumanaidiagnosisconfig_digitalhumanalert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalHumanCommandTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="command_type",
                    ),
                ),
                (
                    "command_payload",
                    models.TextField(
                        blank=True, default="", verbose_name="command_payload"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_task_rows",
                        to="app.digitalhumandevice",
                        verbose_name="device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Human Command Task",
                "verbose_name_plural": "Digital Human Command Tasks",
                "db_table": "dh_command_task",
            },
        ),
        migrations.CreateModel(
            name="DigitalHumanCommandResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="success")),
                (
                    "result_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="result_message",
                    ),
                ),
                (
                    "result_payload",
                    models.TextField(
                        blank=True, default="", verbose_name="result_payload"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
                ),
                (
                    "command_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_rows",
                        to="app.digitalhumancommandtask",
                        verbose_name="command_task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Human Command Result",
                "verbose_name_plural": "Digital Human Command Results",
                "db_table": "dh_command_result",
            },
        ),
        migrations.AddIndex(
            model_name="digitalhumancommandtask",
            index=models.Index(
                fields=["device", "status"], name="idx_dhcmd_device_status"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumancommandtask",
            index=models.Index(
                fields=["status", "create_time"], name="idx_dhcmd_status_time"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalhumancommandresult",
            index=models.Index(
                fields=["command_task", "create_time"], name="idx_dhcmdres_task_time"
            ),
        ),
    ]
