# Generated by Django 4.2 on 2026-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0061_digitalhumancommandtask_digitalhumancommandresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_byte_size",
            field=models.IntegerField(default=0, verbose_name="screenshot_byte_size"),
        ),
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_content_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="screenshot_content_type",
            ),
        ),
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_object_bucket",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="screenshot_object_bucket",
            ),
        ),
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_object_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="screenshot_object_key",
            ),
        ),
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_storage_path",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="screenshot_storage_path",
            ),
        ),
        migrations.AddField(
            model_name="digitalhumandevice",
            name="screenshot_storage_url",
            field=models.TextField(
                blank=True, default="", verbose_name="screenshot_storage_url"
            ),
        ),
    ]
