apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beacon-cloud-saas-v1.fullname" . }}-config
  labels:
    {{- include "beacon-cloud-saas-v1.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.config | nindent 4 }}
