{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beacon-cloud-saas-v1.serviceAccountName" . }}
  labels:
    {{- include "beacon-cloud-saas-v1.labels" . | nindent 4 }}
{{- end }}
