apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-cloud-saas-v1.fullname" . }}
  labels:
    {{- include "beacon-cloud-saas-v1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.beaconCloud.service.type }}
  selector:
    {{- include "beacon-cloud-saas-v1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: beacon-cloud
  ports:
    - name: http
      port: {{ .Values.beaconCloud.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-cloud-saas-v1.postgresName" . }}
  labels:
    {{- include "beacon-cloud-saas-v1.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "beacon-cloud-saas-v1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-cloud-saas-v1.minioName" . }}
  labels:
    {{- include "beacon-cloud-saas-v1.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "beacon-cloud-saas-v1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
